<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-25T16:08:39 IST" name="Suite" finished-at="2024-09-25T16:08:59 IST" duration-ms="19926">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" name="submitOrder" class="com.nithin.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.LoginErrorValidation()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" name="LoginErrorValidation" class="com.nithin.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="productValiadtion">
        <method signature="ErrorValidationTest.productErrorValidation()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" name="productErrorValidation" class="com.nithin.tests.ErrorValidationTest"/>
      </group> <!-- productValiadtion -->
    </groups>
    <test started-at="2024-09-25T16:08:39 IST" name="SubmitOrder Test" finished-at="2024-09-25T16:08:59 IST" duration-ms="19926">
      <class name="com.nithin.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:39 IST" name="launchApplication" finished-at="2024-09-25T16:08:43 IST" duration-ms="3707" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:43 IST" name="submitOrder" data-provider="testdata3" finished-at="2024-09-25T16:08:46 IST" duration-ms="3583" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Batman123@, product=ZARA COAT 3, email=batman@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:46 IST" name="tearDown" finished-at="2024-09-25T16:08:46 IST" duration-ms="138" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:46 IST" name="launchApplication" finished-at="2024-09-25T16:08:49 IST" duration-ms="2427" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:49 IST" name="submitOrder" data-provider="testdata3" finished-at="2024-09-25T16:08:52 IST" duration-ms="3401" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Batman123@, product=ADIDAS ORIGINAL, email=batman@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:52 IST" name="tearDown" finished-at="2024-09-25T16:08:52 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:52 IST" name="launchApplication" finished-at="2024-09-25T16:08:55 IST" duration-ms="2392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:55 IST" name="orderHistoryTest" data-provider="testData" finished-at="2024-09-25T16:08:55 IST" depends-on-methods="com.nithin.tests.SubmitOrderTest.submitOrder" duration-ms="499" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[batman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Batman123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ZARA COAT 3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:55 IST" name="tearDown" finished-at="2024-09-25T16:08:55 IST" duration-ms="79" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:55 IST" name="launchApplication" finished-at="2024-09-25T16:08:58 IST" duration-ms="2611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderHistoryTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:58 IST" name="orderHistoryTest" data-provider="testData" finished-at="2024-09-25T16:08:58 IST" depends-on-methods="com.nithin.tests.SubmitOrderTest.submitOrder" duration-ms="621" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[batman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Batman123@]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ADIDAS ORIGINAL]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.SubmitOrderTest@2dc9b0f5]" started-at="2024-09-25T16:08:58 IST" name="tearDown" finished-at="2024-09-25T16:08:59 IST" duration-ms="141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.nithin.tests.SubmitOrderTest -->
    </test> <!-- SubmitOrder Test -->
    <test started-at="2024-09-25T16:08:39 IST" name="Error Validation Test" finished-at="2024-09-25T16:08:58 IST" duration-ms="19800">
      <class name="com.nithin.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:39 IST" name="launchApplication" finished-at="2024-09-25T16:08:42 IST" duration-ms="2885" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:42 IST" name="LoginErrorValidation" finished-at="2024-09-25T16:08:42 IST" duration-ms="311" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [div] but found [Incorrect emaile or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [div] but found [Incorrect emaile or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.nithin.tests.ErrorValidationTest.LoginErrorValidation(ErrorValidationTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:42 IST" name="tearDown" finished-at="2024-09-25T16:08:42 IST" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:42 IST" name="launchApplication" finished-at="2024-09-25T16:08:46 IST" duration-ms="3475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:46 IST" name="productErrorValidation" finished-at="2024-09-25T16:08:58 IST" duration-ms="12628" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.nithin.tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.nithin.tests.ErrorValidationTest@5d908d47]" started-at="2024-09-25T16:08:58 IST" name="tearDown" finished-at="2024-09-25T16:08:58 IST" duration-ms="114" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.nithin.tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
